### IMPORTANDO LIBRERIA NUMPY

In [ ]:
import numpy as np

# Crea lista de 10 elementos

In [6]:
Lista1 = list(range(1,11))
Lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Transformando la lista a un array

In [7]:

arreglo = np.array(Lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Corroborando el tipo de estructura

In [8]:
type(arreglo)

numpy.ndarray

# Corroborando el tipo de datos del arreglo

In [9]:
arreglo.dtype

dtype('int32')

# Definiendo el array de int32 a float32

In [10]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [11]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Transformando los datos de int32 a float32

In [12]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

# Tambien existe una funcion similar a range ocupando arrays

In [16]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Arreeglo de 2 en 2 utilizando Arange

In [17]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

# ALGUNAS FUNCIONES DE PYTHON

# Obteniendo el promedio de array

In [18]:
promedio = np.mean(arreglo)
promedio

5.5

# Obtener la mediana

In [19]:
mediana = np.median(arreglo)
mediana

5.5

# Desviacion 

# Generacion de un arreglo de 10 elementos de solo unos

In [20]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Transformando el arreglo de unos de puntos flotantes a enteros

In [ ]:
#arreglo_int_ones =

# Utilizando funcion random

# Generando arreglo con numeros aleatorios de 5

In [28]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.87957181, 0.6312534 , 0.46829337, 0.45101368, 0.66840112])

# Generando una matriz aleatoria de 3x3

In [30]:
matriz = np.random.rand(3,3)
matriz

array([[0.15925404, 0.85362642, 0.18745535],
       [0.66955849, 0.80224095, 0.34952238],
       [0.22525857, 0.65986103, 0.29456432]])

# Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5

In [32]:
arreglo_aleatorio2 = np.random.randint(1,5,10)
arreglo_aleatorio2

array([3, 3, 4, 1, 1, 3, 4, 2, 1, 4])

# Generando una matriz aleatorio de 10 numeros enteros del 1 al 100

In [38]:
matriz2 = np.random.randint(1,100,(5,5))
matriz2

array([[49, 50, 99, 87, 86],
       [44, 67,  8, 29, 28],
       [85, 73, 46, 39, 95],
       [ 1, 45, 49, 87, 77],
       [35, 89, 36, 47, 32]])