<h2 style=\"color:green;font-family:Arial\">DIMENSIONES</h2>


In [6]:
import numpy as np

# Generando un array de 12 elemntos enteros con random

In [11]:
arreglo = np.random.randint(1,10,12)
arreglo

array([8, 3, 8, 5, 6, 5, 8, 7, 2, 2, 7, 6])

# obtener la dimension de un arreglo

In [12]:
np.shape(arreglo)

(12,)

# Transformación del vector de 12 elementos a Matriz 4x3 con Reshape

In [13]:
matriz = arreglo.reshape(3,4)
matriz

array([[8, 3, 8, 5],
       [6, 5, 8, 7],
       [2, 2, 7, 6]])

# Transformación del vector de 12 elementos a Matriz 4x3 con Reshape

In [14]:
np.shape(matriz)

(3, 4)

# Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape

In [15]:
matriz = arreglo.reshape(3,4)
matriz

array([[8, 3, 8, 5],
       [6, 5, 8, 7],
       [2, 2, 7, 6]])

# Creando un tensor

In [16]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]